apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-16T01:36:54Z"
  generation: 1
  labels:
    app: javascript-base-module
  name: javascript-base-module
  namespace: default
  resourceVersion: "39085"
  selfLink: /apis/apps/v1/namespaces/default/deployments/javascript-base-module
  uid: 518acf37-0175-46b5-8b9f-a2535f5835ee
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: javascript-base-module
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javascript-base-module
    spec:
      containers:
      - image: caprilespe/javascript-base-module:v1
        imagePullPolicy: IfNotPresent
        name: javascript-base-module
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-09-16T01:36:54Z"
    lastUpdateTime: "2021-09-16T01:37:32Z"
    message: ReplicaSet "javascript-base-module-655f74577d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-09-16T01:37:33Z"
    lastUpdateTime: "2021-09-16T01:37:33Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
